[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meds-evaluation"
dynamic = ["version"]
authors = [
    { name = "Kamilė Stankevičiūtė", email = "kamile.stankeviciute@cst.cam.ac.uk" },
    { name = "Vincent Jeanselme", email = "vincent.jeanselme@mrc-bsu.cam.ac.uk" },
    { name = "Matthew McDermott", email = "mattmcdermott8@gmail.com" },
]
description = "A module for evaluating the predictions of the models trained on MEDS datasets."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars>=0.20.8",
    "pyarrow>=14.0.0",
    "numpy>=1.24; python_version < '3.12'",
    "numpy>=1.26; python_version >= '3.12'",
    "scikit-learn>=1.2; python_version < '3.12'",
    "scikit-learn>=1.3.1; python_version >= '3.12'",
    "hydra-core>=1.3",
    "meds>=0.4.0,<0.5",
    "flexible_schema>=0.1,<0.2",
]

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = [
  "--color=yes",
  "--doctest-modules",
  "--ignore=docs",
]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "ELLIPSIS"]

[project.optional-dependencies]
dev = ["pre-commit<4"]
tests = ["pytest>=7", "pytest-cov>=4"]

[project.scripts]
meds-evaluation-cli = "meds_evaluation.__main__:main"

[project.urls]
Homepage = "https://github.com/kamilest/meds-evaluation"
Issues = "https://github.com/kamilest/meds-evaluation/issues"
